In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Sample_Data_Ingestion.csv")
df.head()

,Server_ID,Hostname,IP_Address,OS_Type,Server_Location,CPU_Utilization (%),Memory_Usage (%),Disk_IO (%),Network_Traffic_In (MB/s),Network_Traffic_Out (MB/s),Uptime (Hours),Downtime (Hours),Admin_Name,Admin_Email,Admin_Phone,Log_Timestamp
0,536c9e75-40a1-4a74-8ca6-c6abaec13999,srv-web02,100.33.3.46,Windows Server 2022,"Berlin, Germany",28.10,88.60,28.36,31.13,52.54,18.49,5.51,John Duarte,laurasolomon@example.net,+77 1834560143,11-03-2025 16:45
1,26bae71d-c025-4082-9484-ef7aa9e04836,srv-web02,249.168.171.15,Ubuntu 20.04,"London, UK",49.72,84.35,73.89,123.34,97.10,19.71,4.29,Abigail Montgomery,sherripatterson@example.com,+10 3791349757,25-01-2025 10:59
2,454de38a-5961-490f-9d46-d20663a36baf,srv-backup02,248.247.52.48,Red Hat Enterprise Linux,"New York, USA",44.72,57.64,14.94,69.60,112.81,18.64,5.36,David Jones,veronicanavarro@example.net,+38 9503876034,29-01-2025 08:31
3,8b8a3f40-1b67-4fe6-a65e-93fd07f317f7,srv-web02,87.221.187.138,Red Hat Enterprise Linux,"New York, USA",37.69,97.97,71.46,62.97,148.51,18.14,5.86,Dominic Richards,frankdawson@example.org,+93 2330701744,01-03-2025 16:49
4,375cb3db-89d3-4705-af4a-8f829cce1928,srv-app02,168.8.91.217,Windows Server 2022,"Tokyo, Japan",63.97,67.31,96.46,45.33,131.50,22.78,1.22,Paul Edwards,hgibson@example.com,+29 9075330226,21-02-2025 11:02

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Server_ID                   200 non-null    object
 1   Hostname                    200 non-null    object
 2   IP_Address                  200 non-null    object
 3   OS_Type                     200 non-null    object
 4   Server_Location             200 non-null    object
 5   CPU_Utilization (%)         200 non-null    float64
 6   Memory_Usage (%)            200 non-null    float64
 7   Disk_IO (%)                 200 non-null    float64
 8   Network_Traffic_In (MB/s)   200 non-null    float64
 9   Network_Traffic_Out (MB/s)  200 non-null    float64
 10  Uptime (Hours)              200 non-null    float64
 11  Downtime (Hours)            200 non-null    float64
 12  Admin_Name                  200 non-null    object
 13  Admin_Email                 200 non-null    object
 14  Admin_Phone                 200 non-null    object
 15  Log_Timestamp               200 non-null    object
dtypes: float64(7), object(9)
memory usage: 25.1+ KB

In [4]:
df.isnull().sum()

Server_ID                     0
Hostname                      0
IP_Address                    0
OS_Type                       0
Server_Location               0
CPU_Utilization (%)           0
Memory_Usage (%)              0
Disk_IO (%)                   0
Network_Traffic_In (MB/s)     0
Network_Traffic_Out (MB/s)    0
Uptime (Hours)                0
Downtime (Hours)              0
Admin_Name                    0
Admin_Email                   0
Admin_Phone                   0
Log_Timestamp                 0
dtype: int64

In [5]:
df = df.dropna()

In [6]:
df.to_csv("cleaned_data.csv", index=False)

Data Transformation

In [9]:
df["CPU_Utilization (%)"].describe()

count    200.000000
mean      57.303850
std       25.590557
min       10.570000
25%       36.287500
50%       57.040000
75%       80.370000
max       99.300000
Name: CPU_Utilization (%), dtype: float64

In [10]:
df["Memory_Usage (%)"].describe()

count    200.000000
mean      60.142550
std       24.139824
min       20.030000
25%       38.920000
50%       60.075000
75%       81.412500
max       99.920000
Name: Memory_Usage (%), dtype: float64

In [11]:
df["Disk_IO (%)"].describe()

count    200.000000
mean      55.179150
std       26.267816
min       10.090000
25%       31.667500
50%       58.440000
75%       76.812500
max       99.650000
Name: Disk_IO (%), dtype: float64

In [12]:
df["Network_Traffic_In (MB/s)"].describe()

df["Network_Traffic_Out (MB/s)"].describe()

count    200.000000
mean      79.728800
std       40.401318
min       10.240000
25%       45.207500
50%       80.950000
75%      116.290000
max      149.250000
Name: Network_Traffic_Out (MB/s), dtype: float64

In [13]:
df["Server_Load"] = df["CPU_Utilization (%)"].apply(
    lambda x: "High Load" if x > 80 else "Normal Load"
)

In [14]:
df.head()

,Server_ID,Hostname,IP_Address,OS_Type,Server_Location,CPU_Utilization (%),Memory_Usage (%),Disk_IO (%),Network_Traffic_In (MB/s),Network_Traffic_Out (MB/s),Uptime (Hours),Downtime (Hours),Admin_Name,Admin_Email,Admin_Phone,Log_Timestamp,Server_Load
0,536c9e75-40a1-4a74-8ca6-c6abaec13999,srv-web02,100.33.3.46,Windows Server 2022,"Berlin, Germany",28.10,88.60,28.36,31.13,52.54,18.49,5.51,John Duarte,laurasolomon@example.net,+77 1834560143,11-03-2025 16:45,Normal Load
1,26bae71d-c025-4082-9484-ef7aa9e04836,srv-web02,249.168.171.15,Ubuntu 20.04,"London, UK",49.72,84.35,73.89,123.34,97.10,19.71,4.29,Abigail Montgomery,sherripatterson@example.com,+10 3791349757,25-01-2025 10:59,Normal Load
2,454de38a-5961-490f-9d46-d20663a36baf,srv-backup02,248.247.52.48,Red Hat Enterprise Linux,"New York, USA",44.72,57.64,14.94,69.60,112.81,18.64,5.36,David Jones,veronicanavarro@example.net,+38 9503876034,29-01-2025 08:31,Normal Load
3,8b8a3f40-1b67-4fe6-a65e-93fd07f317f7,srv-web02,87.221.187.138,Red Hat Enterprise Linux,"New York, USA",37.69,97.97,71.46,62.97,148.51,18.14,5.86,Dominic Richards,frankdawson@example.org,+93 2330701744,01-03-2025 16:49,Normal Load
4,375cb3db-89d3-4705-af4a-8f829cce1928,srv-app02,168.8.91.217,Windows Server 2022,"Tokyo, Japan",63.97,67.31,96.46,45.33,131.50,22.78,1.22,Paul Edwards,hgibson@example.com,+29 9075330226,21-02-2025 11:02,Normal Load

In [16]:
df["Log_Timestamp"] = pd.to_datetime(df["Log_Timestamp"], dayfirst=True)

In [17]:
df["Log_Timestamp"].head()

0   2025-03-11 16:45:00
1   2025-01-25 10:59:00
2   2025-01-29 08:31:00
3   2025-03-01 16:49:00
4   2025-02-21 11:02:00
Name: Log_Timestamp, dtype: datetime64[ns]

In [18]:
df["Year"] = df["Log_Timestamp"].dt.year
df["Month"] = df["Log_Timestamp"].dt.month
df["Day"] = df["Log_Timestamp"].dt.day
df["Hour"] = df["Log_Timestamp"].dt.hour

In [19]:
df.to_csv("processed_server_data.csv", index=False)